site_name: TechEmpower Framework Benchmarks
site_url: http://frameworkbenchmarks.readthedocs.org/en/latest
site_description: Documentation for TechEmpower Framework Benchmarks.
site_favicon: img/favicon.png
repo_url: https://github.com/TechEmpower/TFB-Documentation
repo_name: TFB-Documentation
theme: readthedocs

pages:
- Home: 'index.md'
- Project Information:
  - 'Project Information Overview': 'Project-Information/index.md'
  - 'Basic Concepts' : 'Project-Information/Concepts.md'
  - 'Framework Tests' : 'Project-Information/Framework-Tests.md'
  - 'Environment' : 'Project-Information/Environment.md'
  - 'Travis-CI' : 'Project-Information/Travis-CI.md'
  - 'Expected Questions' : 'Project-Information/Expected-Questions.md'
  - 'Results Website' : 'Project-Information/Results-Website.md'
- Development:
  - 'Development Overview': 'Development/index.md'
  - 'Getting Started': 'Development/Getting-Started.md'
  - 'Contributing Guide': 'Development/Contributing-Guide.md'
  - 'Installation Guide': 'Development/Installation-Guide.md'
  - 'Add Framework or Tests': 'Development/Add-Frameworks-or-Tests.md'
  - 'Testing and Debugging': 'Development/Testing-and-Debugging.md'
  - 'Add Benchmark Scripts': 'Development/Add-Benchmark-Scripts.md'
  - 'Readme Formats': 'Development/Readme-Formats.md'
- Benchmarking:
  - 'Benchmarking Overview': 'Benchmarking/index.md'
  - 'Getting Started': 'Benchmarking/Getting-Started-Benchmarking.md'
  - 'Run the Benchmark': 'Benchmarking/Running-the-Benchmark.md'
- Codebase:
  - 'Codebase Overview': 'Codebase/index.md'
  - 'Configuration File': 'Codebase/Configuration-File.md'
  - 'Framework Files': 'Codebase/Framework-Files.md'
  - 'Summary of Script Directories': 'Codebase/Summary-of-Script-Directories.md'
- About:
  - 'Framework Benchmarks': 'About/Framework-Benchmarks.md'
  - 'TechEmpower': 'About/TechEmpower.md'
  - 'Documentation': 'About/Documentation.md'
  - 'License': 'About/License.md'
- Support:
  - 'Support Overview': 'Support/index.md'
  - 'Join the Conversation': 'Support/Converse.md'
  - 'FAQ': 'Support/FAQ.md'
